magi_ch_55_frieren_essential_text = [
    [],
    [],
    [
        "I more or less get the picture now.",
        'You people are buying time for Friedman to defeat this "Spiegel", the "Reflective Water Demon".',
        "Well, for the clones, we've already dealt with three of them.",
        "It seems this discussion will be quick then.",
        "In that case-",
    ],
    [
        "..... Oh my.",
        "It seems Sense-san's clone got crushed just now.",
        "...This mama. The one who took it down must be libel, the third- class mage.",
    ],
    ["What a surprising outcome.", "You think? That match-up's pretty off."],
    [
        "A battle between images is akin to a rock- paper-scissors match, after all.",
        "Albert a rock-paper- scissors match",
        "that is extremely complex, difficult to read and involves a myriad of moves.",
    ],
    [
        "So you would like to increase the number of available moves we have, by how- ever little it may be.",
        "Very well. I'll help you hold back the clones.",
    ],
    [
        "I'm not the type to trust others, but-",
        "I'm not stupid enough to just let a winning horse that's shaking its backside get away, either.",
    ],
    [
        "...Currently, there are two dangerous clones that absolutely must be stopped.",
        "And I have identified the location of one, which is Denken- san's clone.",
        "I hope you people can deal with that one.",
    ],
    [
        "Please leave the other clone, Fern-sam's, to me.",
        "It seems that child is particularly skilled in masking her mana.",
    ],
    [
        "I would be able to concentrate on mana detection easier alone.",
        "After all, if we do not find it, a surprise attack would likely lead to casualties.",
        "Could you really handle it alone?",
        "That child's pretty strong.",
    ],
    ["I am one of many talents, so stopping someone is my forte."],
    [
        "Moreover, I have already confirmed that restraint magic would work on it as I have tested that on the real body.",
        "I cannot move...",
        "Poke poke",
    ],
    ["Well then, shall we go wild?"],
    [
        "Libel.",
        "I'm... not seeing things, right?",
        "Yeah. After all, you can't move, can you, Four- Eyes?",
    ],
    ["My clone has come back."],
    [],
    [],
    ['Does this mean that this will continue on until that "Spiegel" is defeated?'],
    [
        "It's a war of attrition then.",
        "Now this is going to be fun.",
        "You are precisely correct.",
        "Shouldn't we retreat already?",
    ],
    [],
    [],
    [],
    [],
    [],
    [],
    [
        "This opening wouldn't work either, then.",
        "Since Fern can't detect it right now.",
    ],
    [],
    ["I guess I have no choice but to resort to that."],
    [],
    [],
    [
        "Just an opening for wanna detection wouldn`t be enough for us to kill it. would it?",
        "Certainly.",
    ],
    ["I believe a greater opening would permit us victory, but..."],
    ["So you can beat it then.", "In the that case, shall make you that opening."],
    [
        "Are you able to do such a thing?",
        "If I make an opening myself, it will make an even greater one in turn.",
    ],
    [
        "But then Friedman- sawa would",
        "If I concentrate on my defences, it shouldn`t be a fatal wound.",
    ],
    [
        "And then the strategy in that situation is...",
        "Surprise we.",
        "If Ferw believes she can beat it, then she can.",
    ],
    ["How can you be so certain?"],
    ['Well, "I" have always underestimated Fern, after all.'],
    [],
    ["Then that is a relief.", "We have a strong chance of winning now."],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    ["It's still standing...", "But it has taken a fatal injury.", "I shall end it"],
    [],
    [],
    [],
    ["...What happened...?", "...I got attacked...?"],
    [
        "I can't sense her mana at all...",
        "I can't even perceive this attack as magic...",
    ],
    ["Incredible... Frierem- Sama...", "So this is the pimacle of magic, then..."],
    ["However, that is not like you..."],
    ["...Since it is covered all over with openings."],
    [],
    [],
    [
        "You've done well, Fern.",
        "It's likely been eighty years since I was cornered to the point where I'd have to resort to that.",
    ],
    [],
    ["Well then, shall we end things once and for all now?"],
    [],
    [],
    [],
    [],
    [],
    ["So it is over..."],
    [
        "I can't move any- more...",
        "Wirbel, please carry me on your back...",
        "You two always break down, huh...",
    ],
    [],
    [],
    ["So this is the deepest part of the Tomb of the Ruined King..."],
    [
        "You have conquered the Tomb of the Rained King.",
        "A great achievement sufficiently rivalling that of a first- class mage's, which will now leave its mark in history.",
    ],
    [
        "As promised for reaching the deepest part,",
        "you all pass the second stage of the exam.",
    ],
    [],
    ["......So, where did our greatest achievement disappear off to?"],
    [],
    ["It's Dark!!! It's Scary!!!"],
    [],
    ["Ehh...", "Well, I suppose I can under- stand that sentiment."],
    ["Well then, the second stage of the exam is now over."],
    [
        "...It can surprisingly use recovery magic too.",
        "What'cha think? Isn't that incredible?",
        "Who are you, exactly?",
    ],
    ["Yeah, it's all in your 4/7", "A few"],
]

total_char = 0

for panel_text_arr in magi_ch_55_frieren_essential_text:
    for text in panel_text_arr:
        total_char += len(text)

print(total_char)
